# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
  
    config.vm.define vm_name = "controlplane" do |config|
        config.vm.hostname = "controlplane"
        config.vm.network :private_network, ip: "192.168.10.101"
        config.vm.provider :virtualbox do |vb|
            vb.memory = 2048
            vb.cpus = 2
        end
    end
  
    (1..3).each do |i|
        config.vm.define vm_name = "worker-#{i}" do |config|
            config.vm.hostname = "worker-#{i}"
            config.vm.network :private_network, ip: "192.168.10.#{i+110}"
        end
    end
    
end